import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { useIsMobile } from "@/utils/responsive";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setValue] = useState("");
  const [message, setMessage] = useState({ message: "", status: "" });
  const isMobile = useIsMobile();

  const onFinish = async (e: any) => {
    e.preventDefault();
    const res = await fetch("/api/waitlist", {
      body: JSON.stringify({ email: value }),
      method: "POST",
    });

    const resJson = await res.json();

    if (res.status === 500) {
      setMessage({ message: resJson.message, status: "error" });
    } else {
      setMessage({ message: resJson.message, status: "success" });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className} relative`}>
        <div className={styles.description}>
          <p>rizzGPT</p>
        </div>

        <div
          className={styles.center}
          style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
          }}
        >
          <div
            style={{ position: "relative", top: "-64px" }}
            className={isMobile ? `` : `right-32`}
          >
            <div
              style={{
                position: "relative",
                top: isMobile ? "0px" : "32px",
                display: "flex",
                justifyContent: "center",
              }}
            >
              <Image
                src="/monocle-mock.png"
                alt="monocle-mock"
                className={`contrast-150 brightness-95 opacity-75 ${
                  isMobile ? "" : "-rotate-25"
                }`}
                // 1.78
                width={isMobile ? 1068 : 445}
                height={isMobile ? 700 : 250}
                style={{ maxWidth: isMobile ? "175%" : "100%" }}
                priority
              />
            </div>
            {!isMobile && (
              <Image
                src="/monocle-mock-2.png"
                alt="monocle-mock-2"
                className={`contrast-150 brightness-95 opacity-80 relative bottom-8 ${
                  isMobile ? "left-32" : "left-64"
                }`}
                // 1.78
                width={isMobile ? 890 : 445}
                height={isMobile ? 500 : 250}
                priority
              />
            )}
          </div>
        </div>

        <div className={styles.waitlist}>
          <div className="mb-2">Join waitlist</div>
          <div className="flex">
            <form onSubmit={onFinish}>
              <input
                type="email"
                value={value}
                placeholder="Enter your email"
                className={`rounded-xl bg-transparent text-white px-3 py-2 ${styles.inputGlow}`}
                onChange={(e) => setValue(e.currentTarget.value)}
              />
              <input
                type="submit"
                value="Go"
                className="ml-4 h-full cursor-pointer border-b-[#210D21] border-b-2"
              />
            </form>
          </div>
          {message?.status === "success" && (
            <span style={{ color: "#53C31B" }} className={inter.className}>
              {message.message}
            </span>
          )}
          {message?.status === "error" && (
            <span style={{ color: "#FF4D4E" }} className={inter.className}>
              {message.message}
            </span>
          )}
          {/* <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a> */}
        </div>
      </main>
    </>
  );
}
